#!/usr/bin/env python3
"""Quick test to verify pydantic models work"""

from entidades.cliente import Cliente
from entidades.sucursal import Sucursal
from entidades.orden_compra import OrdenCompra, EstadoOrden
from entidades.detalle_orden import DetalleOrden
from decimal import Decimal
from datetime import datetime

# Test Cliente
cliente = Cliente(
    id_cliente=100,
    name="Juan",
    last_name="Pérez",
    email="juan@example.com",
    phone="5551234567"
)
print(f"✓ Cliente created: {cliente.name} {cliente.last_name}")

# Test Sucursal
sucursal = Sucursal(
    id=1,
    nombre="Sucursal Centro",
    codigo_sucursal="SC001",
    calle="Av. Principal",
    numero="123",
    colonia="Centro",
    ciudad="Ciudad de México",
    estado="CDMX",
    pais="México",
    codigo_postal="01000",
    latitud=19.4326,
    longitud=-99.1332
)
print(f"✓ Sucursal created: {sucursal.nombre}")

# Test OrdenCompra
orden = OrdenCompra(
    id=1,
    cliente_id=cliente.id_cliente,
    sucursal_id=sucursal.id,
    fecha_orden=datetime(2026, 4, 3, 10, 30),
    estado=EstadoOrden.PENDIENTE,
    metodo_pago="tarjeta_credito",
    total=Decimal("1500.00")
)
print(f"✓ OrdenCompra created: Estado={orden.estado.value}, Total={orden.total}")

# Test DetalleOrden
detalle = DetalleOrden(
    id=1, #this would normally be auto-generated by the database,
    orden_id=orden.id,
    producto_id=1,
    cantidad=5,
    precio_unitario=Decimal("100.00"),
    subtotal=Decimal("500.00")
)
print(f"✓ DetalleOrden created: Cantidad={detalle.cantidad}, Subtotal={detalle.subtotal}")

print("\n✓ All models validated successfully!")
